name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-install-cache
      - name: Check formatting with prettier
        run: npm run format:check

  audit:
    runs-on: ubuntu-latest
    needs: [prettier]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-install-cache
      - name: Npm audit
        run: |
          npm config set audit-level critical
          npm audit --registry="https://registry.npmjs.org"

  test:
    runs-on: ubuntu-latest
    needs: [audit]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-install-cache
      - name: Run unit tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [audit]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-install-cache
      - name: Build app
        run: npm run build --if-present
